#pragma once

#include <core/vulkan/enum/VulkanEnum.hpp>

namespace core::vk {

enum class DynamicState {
    Viewport,
    Scissor,
    LineWidth,
    DepthBias,
    BlendConstants,
    DepthBounds,
    StencilCompareMask,
    StencilWriteMask,
    StencilReference,
    ViewportWScaling,
    DiscardRectangle,
    DiscardRectangleEnable,
    DiscardRectangleMode,
    SampleLocations,
    ViewportShadingRatePalette,
    Unused1,
    ViewportCoarseSampleOrder,
    ExclusiveScissorEnable,
    ExclusiveScissor,
    FragmentShadingRate,
    LineStripe,
    CullMode,
    FrontFace,
    PrimitiveTopology,
    ViewportWithCount,
    ScissorWithCount,
    VertexInputBindingStride,
    DepthTestEnable,
    DepthWriteEnable,
    DepthCompareOp,
    DepthBoundsTestEnable,
    StencilTestEnable,
    StencilOp,
    RayTracingPipelineStackSize,
    VertexInput,
    PatchControlPoints,
    RasterizedDiscardEnable,
    DepthBiasEnable,
    StateLogicOp,
    PrimitiveRestartEnable,
    ColorWriteEnable,
    TessellationDomainOrigin,
    DepthClampEnable,
    PolygonMode,
    RasterizationSamples,
    SampleMask,
    AlphaToCoverageEnable,
    AlphaToOneEnable,
    LogicOpEnable,
    ColorBlendEnable,
    ColorBlendEquation,
    ColorWriteMask,
    RasterizationStream,
    ConservativeRasterizationMode,
    ExtraPrimitiveOverestimationSize,
    DepthClipEnable,
    SampleLocationsEnable,
    ColorBlendAdvanced,
    ProvokingVertexMode,
    LineRasterizationMode,
    LineStippleEnable,
    DepthClipNegativeOneToOne,
    ViewportWScalingEnable,
    ViewportSwizzle,
    CoverageToColorEnable,
    CoverageModulationMode,
    CoverageModulationTableEnable,
    CoverageModulationTable,
    ShadingRateImageEnable,
    RepresentativeFragmentTestEnable,
    CoverageReductionMode,
    AttachmentFeedbackLoopEnable,
    DepthClampRange,

    Count,
};

} // namespace core::vk

CORE_VK_REGISTER_ENUM(DynamicState,
    { ViewportWScaling,             1'000'087'000 },
    { DiscardRectangle,             1'000'099'000 },
    { SampleLocations,              1'000'143'000 },
    { ViewportShadingRatePalette,   1'000'164'004 },
    { ExclusiveScissorEnable,       1'000'205'000 },
    { FragmentShadingRate,          1'000'226'000 },
    { LineStripe,                   1'000'259'000 },
    { CullMode,                     1'000'267'000 },
    { RayTracingPipelineStackSize,  1'000'347'000 },
    { VertexInput,                  1'000'352'000 },
    { PatchControlPoints,           1'000'377'000 },
    { ColorWriteEnable,             1'000'381'000 },
    { TessellationDomainOrigin,     1'000'455'002 },
    { AttachmentFeedbackLoopEnable, 1'000'524'000 },
    { DepthClampRange,              1'000'582'000 }
);
