target_sources(mc
    PRIVATE
        Allocator.cpp
        AllocatorBuilder.cpp
        Capabilities.cpp
        Check.cpp
        ColorSpace.cpp
        Device.cpp
        DeviceBuilder.cpp
        ErrorCallbacks.cpp
        Extensions.cpp
        Features.cpp
        Format.cpp
        Image.cpp
        ImageUsage.cpp
        Instance.cpp
        InstanceBuilder.cpp
        Layers.cpp
        MemoryProperty.cpp
        PhysicalDeviceSelector.cpp
        PhysicalDeviceType.cpp
        PresentMode.cpp
        QueueFamily.cpp
        Surface.cpp
        SurfaceTransform.cpp
        VulkanVersion.cpp
)
add_subdirectory(internal)
