if(NOT DEFINED ENV{MC_MSAN_LIBCXX_PREFIX})
    message(FATAL_ERROR "MC_MSAN_LIBCXX_PREFIX must point to the MemorySanitizer-instrumented libc++ installation")
endif()

set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
if(NOT DEFINED ENV{MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE})
    message(FATAL_ERROR "MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE must select Clang for Linux analysis ports")
endif()
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "$ENV{MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
set(MC_MSAN_FLAGS "-fsanitize=memory -fsanitize-memory-track-origins=2 -fno-omit-frame-pointer")
set(VCPKG_C_FLAGS "${MC_MSAN_FLAGS}")
set(VCPKG_CXX_FLAGS "${MC_MSAN_FLAGS} -stdlib=libc++ -isystem $ENV{MC_MSAN_LIBCXX_PREFIX}/include/c++/v1")
set(VCPKG_LINKER_FLAGS "-fsanitize=memory -stdlib=libc++ -L$ENV{MC_MSAN_LIBCXX_PREFIX}/lib -Wl,-rpath,$ENV{MC_MSAN_LIBCXX_PREFIX}/lib")
