set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
if(NOT DEFINED ENV{MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE})
    message(FATAL_ERROR "MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE must select Clang for Linux analysis ports")
endif()
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "$ENV{MC_VCPKG_CHAINLOAD_TOOLCHAIN_FILE}")
set(VCPKG_C_FLAGS "-fsanitize=leak -fno-omit-frame-pointer")
set(VCPKG_CXX_FLAGS "-fsanitize=leak -fno-omit-frame-pointer -stdlib=libc++")
set(VCPKG_LINKER_FLAGS "-fsanitize=leak -stdlib=libc++")
