macro(MAIN_MODULE name)
    add_executable(${name})
    if(MINECRAFT_CLONE_TESTING)
        if (TESTS)
            target_sources(${name} PRIVATE ${TESTS})
        endif()
    endif()

    if(SOURCES)
        target_sources(${name} PRIVATE ${SOURCES})
    endif()
    if(DEPS)
        target_link_libraries(${name} PRIVATE ${DEPS})
    endif()
    if(INCLUDES)
        target_include_directories(${name} PRIVATE ${INCLUDES})
    endif() 
    if(SYSTEM_INCLUDES)
        target_include_directories(${name} SYSTEM PRIVATE ${SYSTEM_INCLUDES})
    endif()
endmacro()

macro(SUBMODULE path)
    if(LOCAL_SOURCES)
        list(TRANSFORM LOCAL_SOURCES PREPEND ${path}/)
        set(SOURCES "${SOURCES};${LOCAL_SOURCES}" PARENT_SCOPE)
    endif()
    if(LOCAL_TESTS)
        list(TRANSFORM LOCAL_TESTS PREPEND ${path}/)
        set(TESTS "${TESTS};${LOCAL_TESTS}" PARENT_SCOPE)
    endif()
endmacro()
