macro(MAIN_MODULE name)
    add_executable(${name})
    if(MINECRAFT_CLONE_TESTING)
        if (TESTS)
            target_sources(${name} PRIVATE ${TESTS})
        endif()
    endif()

    if(SOURCES)
        target_sources(${name} PRIVATE ${SOURCES})
    endif()
    if(DEPS)
        target_link_libraries(${name} PRIVATE ${DEPS})
    endif()
    if(INCLUDES)
        target_include_directories(${name} PRIVATE ${INCLUDES})
    endif() 
    if(SYSTEM_INCLUDES)
        target_include_directories(${name} SYSTEM PRIVATE ${SYSTEM_INCLUDES})
    endif()
endmacro()
